// The canon graph, exported from YAML by arc-core's export-canon.py.
//
// In the monorepo this was a checked-in artifact at viewer/public/canon.json,
// regenerated by hand. That cannot survive the split — the frontend repo has
// neither python nor the canon — so the backend generates it on demand and
// serves it at GET /api/canon, invalidating whenever the agent writes canon.
import { execFileSync } from 'node:child_process'
import path from 'node:path'
import { CORE, PYTHON, STORY } from './config'

let cached: string | null = null

/** Run one of arc-core's python tools against the configured story. */
export function runTool(script: string, args: string[] = []): { ok: boolean; output: string } {
  try {
    const out = execFileSync(PYTHON, [path.join(CORE, 'tools', script), STORY, ...args], {
      cwd: CORE, encoding: 'utf8', timeout: 30_000, maxBuffer: 32 * 1024 * 1024,
    })
    return { ok: true, output: out }
  } catch (e: any) {
    return { ok: false, output: String(e.stdout ?? '') + String(e.stderr ?? e.message ?? e) }
  }
}

/** The canon graph as a JSON string. Cached until invalidateCanon(). */
export function canonJson(): string {
  if (cached !== null) return cached
  const res = runTool('export-canon.py')   // no out path — writes the graph to stdout
  if (!res.ok) throw new Error(`export-canon.py failed:\n${res.output}`)
  cached = res.output
  return cached
}

export function invalidateCanon(): void {
  cached = null
}

export function validateStory(): { ok: boolean; output: string } {
  const res = runTool('validate.py')
  return { ok: res.ok, output: res.output.trim() }
}
