// The canon graph, exported from YAML by arc-core's export-canon.py.
//
// In the monorepo this was a checked-in artifact at viewer/public/canon.json,
// regenerated by hand. That cannot survive the split — the frontend repo has
// neither python nor the canon — so the backend generates it on demand and
// serves it at GET /api/canon, invalidating whenever the agent writes canon.
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { CORE, PYTHON, STORY } from './config'
import { HttpError } from './http'

let cached: string | null = null
let cachedStamp = ''

/** Newest mtime across canon/, so a hand-edit to the YAML is picked up too —
 *  not just writes made through the agent. Cheap: ~40 stats on this story. */
function canonStamp(dir = path.join(STORY, 'canon')): string {
  let newest = 0
  const walk = (d: string) => {
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
      const p = path.join(d, e.name)
      if (e.isDirectory()) walk(p)
      else if (e.name.endsWith('.yaml')) newest = Math.max(newest, fs.statSync(p).mtimeMs)
    }
  }
  walk(dir)
  return String(newest)
}

/** Run one of arc-core's python tools against the configured story. */
export function runTool(script: string, args: string[] = []): { ok: boolean; output: string } {
  try {
    const out = execFileSync(PYTHON, [path.join(CORE, 'tools', script), STORY, ...args], {
      cwd: CORE, encoding: 'utf8', timeout: 30_000, maxBuffer: 32 * 1024 * 1024,
    })
    return { ok: true, output: out }
  } catch (e: any) {
    return { ok: false, output: String(e.stdout ?? '') + String(e.stderr ?? e.message ?? e) }
  }
}

/** The canon graph as a JSON string, re-exported whenever canon/ changes. */
export function canonJson(): string {
  const stamp = canonStamp()
  if (cached !== null && stamp === cachedStamp) return cached
  const res = runTool('export-canon.py')   // no out path — writes the graph to stdout
  if (!res.ok) {
    // The full tool output (often a python traceback) belongs in the backend
    // log, not the browser.
    console.error('[error] export-canon.py failed:\n' + res.output)
    throw new HttpError(500, 'canon export failed — see the backend log, or run tools/validate.py on the story')
  }
  cached = res.output
  cachedStamp = stamp
  return cached
}

export function invalidateCanon(): void {
  cached = null
  cachedStamp = ''
}

export function validateStory(): { ok: boolean; output: string } {
  const res = runTool('validate.py')
  return { ok: res.ok, output: res.output.trim() }
}
